apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: k0s-master
      user: k0s
      port: 22
      keyPath: ${K0S_SSH_KEY_PATH:-~/.ssh/id_rsa}
    role: controller
  - ssh:
      address: k0s-worker-1
      user: k0s
      port: 22
      keyPath: ${K0S_SSH_KEY_PATH:-~/.ssh/id_rsa}
    role: worker
  - ssh:
      address: k0s-worker-2
      user: k0s
      port: 22
      keyPath: ${K0S_SSH_KEY_PATH:-~/.ssh/id_rsa}
    role: worker
  k0s:
    version: 1.23.6+k0s.2
